<?php
 echo $this->doctype ();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head>
  <?php echo $this->headMeta ();  ?>
  <?php echo $this->headTitle (); ?>                                                                                
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
 <link rel="stylesheet" href="/zf-mygengo/public/stylesheets/mygengo/base.css" type="text/css" media="screen" />
 <link rel="stylesheet" href="/zf-mygengo/public/stylesheets/mygengo/style.css" type="text/css" media="screen" />
 <link rel="stylesheet" href="/zf-mygengo/public/stylesheets/mygengo/override.css" type="text/css" media="screen" />
 <link rel="stylesheet" href="/zf-mygengo/public/stylesheets/mygengo/scaffold.css" type="text/css" media="screen" />
 <link rel="stylesheet" href="/zf-mygengo/public/stylesheets/mygengo/mugen.css" type="text/css" media="screen" />
 <script src="/zf-mygengo/public/javascripts/jquery.js" type="text/javascript"></script>
 </head>
 <body>
  <div id="container">
    <div id="header">
      <h1><a href="/">myGengo</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#" class="logout"> Logout </a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li><a href="<?= $this->url(array('controller'=>'jobs', 'module' => 'mygengo'), null, true) ?>">Jobs</a></li>
          <li><a href="<?= $this->url(array('controller'=>'account', 'module' => 'mygengo'), null, true) ?>">Account</a></li>
        </ul>                  
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">  
        <?php if (count($this->messages)) : ?>
        <?php foreach ($this->messages as $message) : ?>
            <div class="message notice">
              <p><?php echo $this->escape($message); ?></p>
            </div>
        <?php endforeach; ?>
        <?php endif; ?>
      </div>
      <div id="main">
        <?php echo $this->layout ()->content; ?>        
        <br />
        <br />
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; Vladimir Penkin</p>
          </div>      
        </div>
      </div>
    </div>    
  </div>      
 </body>
</html>                               