<?php $job = $this->job ?>
<h3>Job review page</h3>

<form accept-charset="UTF-8" action="<?= $this->url(array('controller'=>'jobs', 'action' => 'approve', 'id' => $job->job_id, 'module' => 'mygengo'), null, true) ?>" method="post">  
  <div class='field'>
    Job #<a href="<?= $this->url(array('controller'=>'jobs','action'=>'show','id'=>$job->job_id, 'module' => 'mygengo'), null, true) ?>"><?= $job->job_id ?></a>
  </div>
  <div class='field'>
    <h4>
      Original text
      <br>
      <textarea cols="40" id="body_src" name="body_src" rows="7"><?= $job->body_src ?></textarea>
    </h4>
  </div>
  <div class='field'>
    <h4>
      Preview
      <br>
      <img src="<?= $this->baseUrl() .'/images/mygengo/'. $this->preview ?>" />
    </h4>                                
  </div>
  <div class='field'>
    Please rate the translation
    <br>
    Bad
    <input id="job_rating_1" name="job[rating]" type="radio" value="1" />
    1
    <input id="job_rating_2" name="job[rating]" type="radio" value="2" />
    2
    <input id="job_rating_3" name="job[rating]" type="radio" value="3" />
    3
    <input id="job_rating_4" name="job[rating]" type="radio" value="4" />
    4
    <input id="job_rating_5" name="job[rating]" type="radio" value="5" />
    5
    Good
  </div>
  <div class='field'>
    for_translator
    <br>
    <textarea cols="40" id="job_for_translator" name="job[for_translator]" rows="2"></textarea>
  </div>
  <div class='field'>
    for_mygengo
    <br>
    <textarea cols="40" id="job_for_mygengo" name="job[for_mygengo]" rows="2"></textarea>
  </div>
  <div class='field'>
    Can myGengo use this translation publicly in its examples?
    <br>
    <input id="job_public" name="job[public]" type="checkbox" value="1" />
    Yes, you can use this translation as public example of myGengo service.
  </div>

  <?= $this->partial('jobs/_comments.phtml', array('job' => $job)) ?>

  <input id="job_submit" name="commit" type="submit" value="Approve" />
  |
  <a href="<?= $this->url(array('controller'=>'jobs', 'action' => 'reject', 'id' => $job->job_id, 'module' => 'mygengo'), null, true) ?>">Reject</a>
  |
  <a href="<?= $this->url(array('controller'=>'jobs', 'action' => 'revise', 'id' => $job->job_id, 'module' => 'mygengo'), null, true) ?>">Request corrections</a>
</form>
 