<?php $job = $this->job ?>

<h3>Revise</h3>
<form accept-charset="UTF-8" action="<?= $this->url(array('controller'=>'jobs', 'action' => 'revise_post', 'id' => $job->job_id, 'module' => 'mygengo'), null, true) ?>" method="post">
  <div class='field'>
    Comment
    <br>
    <textarea cols="40" id="job_comment" name="comment" rows="7"></textarea>
  </div>
  <input id="job_submit" name="commit" type="submit" value="Revise" />
</form>

<a href="<?= $this->url(array('controller'=>'jobs','action'=>'show','id'=>$this->job_id, 'module' => 'mygengo'), null, true)?>">Back</a>
